# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy to S3

on:
  push:
    branches:
      - main  # adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <YOUR_AWS_REGION>

      - name: Deploy to S3
        uses: aws-actions/amazon-s3-deploy@v0.1.1
        with:
          args: --acl public-read --follow-symlinks --delete
          bucket-name: <YOUR_S3_BUCKET_NAME>
          local-dir: <LOCAL_DIRECTORY_TO_UPLOAD>
          include: <FILE_PATTERN_TO_INCLUDE>
          exclude: <FILE_PATTERN_TO_EXCLUDE>
